;
; File generated by cc65 v 2.19 - Git 357f64e4e
;
	.fopt		compiler,"cc65 v 2.19 - Git 357f64e4e"
	.setcpu		"65SC02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_tgi_static_stddrv
	.import		_tgi_install
	.import		_tgi_init
	.import		_tgi_clear
	.import		_tgi_setcolor
	.import		_tgi_outtextxy
	.import		_tgi_ioctl
	.export		_main

.segment	"RODATA"

S0002:
	.byte	$48,$65,$6C,$6C,$6F,$20,$57,$6F,$72,$6C,$64,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; tgi_install(tgi_static_stddrv);
;
	lda     #<(_tgi_static_stddrv)
	ldx     #>(_tgi_static_stddrv)
	jsr     _tgi_install
;
; tgi_init();
;
	jsr     _tgi_init
;
; CLI();
;
	cli
;
; while (tgi_busy())
;
L0002:	lda     #$04
	jsr     pusha
	ldx     #$00
	txa
	jsr     _tgi_ioctl
	stx     tmp1
	ora     tmp1
	bne     L0002
;
; tgi_clear();
;
	jsr     _tgi_clear
;
; tgi_setcolor(COLOR_GREEN);
;
	lda     #$0B
	jsr     _tgi_setcolor
;
; tgi_outtextxy(0, 0, "Hello World");
;
	jsr     push0
	jsr     push0
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _tgi_outtextxy
;
; tgi_updatedisplay();
;
	lda     #$04
	jsr     pusha
	ldx     #$00
	lda     #$01
	jsr     _tgi_ioctl
;
; while (1)
;
L0008:	bra     L0008

.endproc

